### ISSUE TITLE
Adjust DD4Hep to work with TBB 2021.1.1

### ISSUE THREAD

**Issue by mrodozov** [AIDASoft/DD4hep#776]
- OS version: e.g. SLC7, CC8
 - Compiler version: e.g GCC 8,9,10
 - DD4hep version: latest commit on master
 - Reproduced by: try to build DD4Hep with TBB 2021.1.1
 - Input: 
 - Output: 
```
 /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc900/external/dd4hep/v01-14x-40905a990db2c099fc0b04fc73ba5fa2/dd4hep-v01-14x/DDDigi/src/DigiKernel.cpp: In constructor 'dd4hep::digi::DigiKernel::DigiKernel(dd4hep::Detector&)':
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc900/external/dd4hep/v01-14x-40905a990db2c099fc0b04fc73ba5fa2/dd4hep-v01-14x/DDDigi/src/DigiKernel.cpp:143:32: error: 'tbb::task_scheduler_init' has not been declared
  143 |   internals->numThreads = tbb::task_scheduler_init::default_num_threads();
      |                                ^~~~~~~~~~~~~~~~~~~
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc900/external/dd4hep/v01-14x-40905a990db2c099fc0b04fc73ba5fa2/dd4hep-v01-14x/DDDigi/src/DigiKernel.cpp: In destructor 'virtual dd4hep::digi::DigiKernel::~DigiKernel()':
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc900/external/dd4hep/v01-14x-40905a990db2c099fc0b04fc73ba5fa2/dd4hep-v01-14x/DDDigi/src/DigiKernel.cpp:165:8: error: 'task_scheduler_init' is not a member of 'tbb'
  165 |   tbb::task_scheduler_init* init = (tbb::task_scheduler_init*)internals->tbbInit;
 ```
 
 - Goal: We'd like to integrate TBB 2021.1.1 into our external packages, for which DD4Hep should build with latest TBB
You can check the logs from the integration attempt 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-623c54/12355/external/dd4hep/v01-14x-40905a990db2c099fc0b04fc73ba5fa2/log
You can also setup the environment with this:

https://github.com/cms-sw/cmsdist/pull/6558#issuecomment-762987107

**Comment by andresailer** [comment]
Just an aside, the CMS relevant code no longer uses TBB #723 so you could probably disable the use of TBB for dd4hep in CMS itself as a workaround.
@cvuosalo @ianna right?

**Comment by mrodozov** [comment]
Yup, it builds, and since -> 723 is merged I removed the flag and DD4hep built.

**Comment by ianna** [comment]
> Just an aside, the CMS relevant code no longer uses TBB #723 so you could probably disable the use of TBB for dd4hep in CMS itself as a workaround.
> @cvuosalo @ianna right?

Yes, we could not fully benefit from having TBB, so we went back to the std containers ;-)
