### ISSUE TITLE
dd4hep for root 6.12 and above

### ISSUE THREAD

**Issue by smuzaffar** [AIDASoft/DD4hep#298]
We are trying to integrate dd4hep v01-05 in https://github.com/cms-sw/cmssw but it failed to build with root version v6-12-04 and root master. Is there any dd4hep version for newer root?
Here is how we configure and built it
```
cmake -DCMAKE_INSTALL_PREFIX=/opt/cmssw/slc6_amd64_gcc630/external/dd4hep/v01-05-cms -DBoost_NO_BOOST_CMAKE=ON -DCMAKE_PREFIX_PATH=/opt/cmssw/slc6_amd64_gcc630/external/clhep/2.4.0.0 -DDD4HEP_USE_XERCESC=ON -DXERCESC_ROOT_DIR=/opt/cmssw/slc6_amd64_gcc630/external/xerces-c/3.1.3-cms -DDD4HEP_USE_PYROOT=ON -DCMAKE_BUILD_TYPE=Release ../dd4hep-v01-05
...
...
[ 13%] Generating G__DD4hepGeo.cxx
cd /opt/cmssw/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/build/DDCore && /opt/cmssw/slc6_amd64_gcc630/lcg/root/6.12.05-ahpamp/bin/rootcling -cint -f G__DD4hepGeo.cxx -s /opt/cmssw/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/build/DDCore/../lib/G__DD4hepGeo -inlineInputHeader -c -p -D__ROOFIT_NOBANNER -DBOOST_SPIRIT_USE_PHOENIX_V3 -DDD4HEP_USE_STDCXX=11 -DDD4HEP_USE_XERCESC -std=c++11 -I/opt/cmssw/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/dd4hep-v01-05/DDCore/include -I/opt/cmssw/slc6_amd64_gcc630/lcg/root/6.12.05-ahpamp/include -I/opt/cmssw/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/dd4hep-v01-05/DDParsers/include -I/opt/cmssw/slc6_amd64_gcc630/external/xerces-c/3.1.3-cms/include /opt/cmssw/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/dd4hep-v01-05/DDCore/include/ROOT/Warnings.h /opt/cmssw/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/dd4hep-v01-05/DDCore/src/GeoDictionary.h /opt/cmssw/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/dd4hep-v01-05/DDCore/include/ROOT/LinkDef.h
In file included from input_line_12:77:
In file included from /opt/cmssw/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/dd4hep-v01-05/DDCore/include/DD4hep/Volumes.h:18:
In file included from /opt/cmssw/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/dd4hep-v01-05/DDCore/include/DD4hep/Shapes.h:19:
In file included from /opt/cmssw/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/dd4hep-v01-05/DDCore/include/DD4hep/Objects.h:36:
In file included from /opt/cmssw/slc6_amd64_gcc630/lcg/root/6.12.05-ahpamp/include/TGeoPhysicalNode.h:15:
In file included from /opt/cmssw/slc6_amd64_gcc630/lcg/root/6.12.05-ahpamp/include/TNamed.h:26:
In file included from /opt/cmssw/slc6_amd64_gcc630/lcg/root/6.12.05-ahpamp/include/TString.h:28:
In file included from /opt/cmssw/slc6_amd64_gcc630/lcg/root/6.12.05-ahpamp/include/RStringView.h:24:
In file included from /opt/cmssw/slc6_amd64_gcc630/external/gcc/6.3.0-cms/bin/../lib/gcc/x86_64-unknown-linux-gnu/6.3.0/../../../../include/c++/6.3.0/experimental/string_view:39:
/opt/cmssw/slc6_amd64_gcc630/external/gcc/6.3.0-cms/bin/../lib/gcc/x86_64-unknown-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/c++14_warning.h:32:2: error: This file requires compiler and library support for the forthcoming ISO C++ 2014 standard. This support is currently experimental, and must be enabled with the -std=c++1y or -std=gnu++1y compiler options.
#error This file requires compiler and library support for the forthcoming \
 ^
In file included from input_line_12:77:
In file included from /opt/cmssw/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/dd4hep-v01-05/DDCore/include/DD4hep/Volumes.h:18:
In file included from /opt/cmssw/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/dd4hep-v01-05/DDCore/include/DD4hep/Shapes.h:19:
In file included from /opt/cmssw/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/dd4hep-v01-05/DDCore/include/DD4hep/Objects.h:36:
In file included from /opt/cmssw/slc6_amd64_gcc630/lcg/root/6.12.05-ahpamp/include/TGeoPhysicalNode.h:15:
In file included from /opt/cmssw/slc6_amd64_gcc630/lcg/root/6.12.05-ahpamp/include/TNamed.h:26:
In file included from /opt/cmssw/slc6_amd64_gcc630/lcg/root/6.12.05-ahpamp/include/TString.h:28:
/opt/cmssw/slc6_amd64_gcc630/lcg/root/6.12.05-ahpamp/include/RStringView.h:32:37: error: no member named 'experimental' in namespace 'std'
   using basic_string_view = ::std::experimental::basic_string_view<_CharT,_Traits>;
                             ~~~~~~~^
/opt/cmssw/slc6_amd64_gcc630/lcg/root/6.12.05-ahpamp/include/RStringView.h:35:12: error: no template named 'basic_string_view'
   typedef basic_string_view<char> string_view;
           ^
/opt/cmssw/slc6_amd64_gcc630/lcg/root/6.12.05-ahpamp/include/RStringView.h:36:12: error: no template named 'basic_string_view'
   typedef basic_string_view<char16_t> u16string_view;
           ^
/opt/cmssw/slc6_amd64_gcc630/lcg/root/6.12.05-ahpamp/include/RStringView.h:37:12: error: no template named 'basic_string_view'
   typedef basic_string_view<char32_t> u32string_view;
           ^
/opt/cmssw/slc6_amd64_gcc630/lcg/root/6.12.05-ahpamp/include/RStringView.h:38:12: error: no template named 'basic_string_view'
   typedef basic_string_view<wchar_t> wstring_view;
           ^
/opt/cmssw/slc6_amd64_gcc630/lcg/root/6.12.05-ahpamp/include/RStringView.h:50:39: error: member reference base type 'std::string_view' (aka 'int') is not a structure or union
      return std::stod(std::string(str.data(), str.size()),pos);
                                   ~~~^~~~~
/opt/cmssw/slc6_amd64_gcc630/lcg/root/6.12.05-ahpamp/include/RStringView.h:50:51: error: member reference base type 'std::string_view' (aka 'int') is not a structure or union
      return std::stod(std::string(str.data(), str.size()),pos);
                                               ~~~^~~~~
/opt/cmssw/slc6_amd64_gcc630/lcg/root/6.12.05-ahpamp/include/RStringView.h:67:51: error: excess elements in scalar initializer
       operator std::string_view() const { return std::string_view(fData,fLength); }
```

**Comment by andresailer** [comment]
The master compiles with root 6.12.04 https://gitlab.cern.ch/CLICdp/DetectorSoftware/DD4hep/-/jobs/939468 
Can you please post the complete output from the cmake command.

**Comment by smuzaffar** [comment]
here is complete outout of cmake. OK , I will try the master now.
```
+ cmake -DCMAKE_INSTALL_PREFIX=/build/muz/h/w/tmp/BUILDROOT/6339c14dbc7e702609ccb7aebd305d11/opt/cmssw/slc6_amd64_gcc630/external/dd4hep/v01-05-cms -DBoost_NO_BOOST_CMAKE=ON -DCMAKE_PREFIX_PATH=/build/muz/h/w/slc6_amd64_gcc630/external/clhep/2.4.0.0 -DDD4HEP_USE_XERCESC=ON -DXERCESC_ROOT_DIR=/build/muz/h/w/slc6_amd64_gcc630/external/xerces-c/3.1.3-cms -DDD4HEP_USE_PYROOT=ON -DCMAKE_BUILD_TYPE=Release ../dd4hep-v01-05
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /build/muz/h/w/slc6_amd64_gcc630/external/gcc/6.3.0-cms/bin/cc
-- Check for working C compiler: /build/muz/h/w/slc6_amd64_gcc630/external/gcc/6.3.0-cms/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /build/muz/h/w/slc6_amd64_gcc630/external/gcc/6.3.0-cms/bin/c++
-- Check for working CXX compiler: /build/muz/h/w/slc6_amd64_gcc630/external/gcc/6.3.0-cms/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- INCLUDING DD4hepBuild.... c++11: c++14:
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- DD4hep_configure_output: set CMAKE_INSTALL_PREFIX to /build/muz/h/w/tmp/BUILDROOT/6339c14dbc7e702609ccb7aebd305d11/opt/cmssw/slc6_amd64_gcc630/external/dd4hep/v01-05-cms
-- ROOT_VERSION: 6.12.05
-- Boost version: 1.63.0
-- Performing Test CXX_FLAG_WORKS__Wall
-- Performing Test CXX_FLAG_WORKS__Wall - Success
-- Adding -Wall to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS__Wextra
-- Performing Test CXX_FLAG_WORKS__Wextra - Success
-- Adding -Wextra to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS__pedantic
-- Performing Test CXX_FLAG_WORKS__pedantic - Success
-- Adding -pedantic to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS__Wshadow
-- Performing Test CXX_FLAG_WORKS__Wshadow - Success
-- Adding -Wshadow to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS__Wformat_security
-- Performing Test CXX_FLAG_WORKS__Wformat_security - Success
-- Adding -Wformat-security to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS__Wno_long_long
-- Performing Test CXX_FLAG_WORKS__Wno_long_long - Success
-- Adding -Wno-long-long to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS__Wdeprecated
-- Performing Test CXX_FLAG_WORKS__Wdeprecated - Success
-- Adding -Wdeprecated to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS__fdiagnostics_color=auto
-- Performing Test CXX_FLAG_WORKS__fdiagnostics_color=auto - Success
-- Adding -fdiagnostics-color=auto to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS_CXX14
-- Performing Test CXX_FLAG_WORKS_CXX14 - Success
-- Performing Test CXX_FLAG_WORKS_CXX11
-- Performing Test CXX_FLAG_WORKS_CXX11 - Success
-- Performing Test CXX_FLAG_WORKS_FTLS_global_dynamic
-- Performing Test CXX_FLAG_WORKS_FTLS_global_dynamic - Success
-- Found XercesC: /build/muz/h/w/slc6_amd64_gcc630/external/xerces-c/3.1.3-cms/lib/libxerces-c.so  
-- +------------------------------------------- <<<< PACKAGE DDParsers >>>> Version: ( 1.2.0 )
-- |++> Package[DDParsers] Uses: ROOT
-- Boost version: 1.63.0
-- |    Package library[DDParsers] -> DDParsers  ...optional: ADD sources src/parsers/*.cpp [dependent on BOOST]
-- |++> Package library[DDParsers] -> DDParsers Uses: BOOST
-- +------------------------------------------- <<<< PACKAGE DDCore >>>> Version: ( 1.2.0 )
-- |++> Package[DDCore] Uses: ROOTDDParsersXERCESC
-- |++> Dictionary[DDCore] -> G__DD4hep Building dictionary ...
-- |++> Dictionary[DDCore] -> G__DD4hep Uses  DEFAULTS
-- |++        exclude: /build/muz/h/w/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/dd4hep-v01-05/DDCore/include/DD4hep/DetFactoryHelper.h
-- |++        exclude: /build/muz/h/w/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/dd4hep-v01-05/DDCore/include/DD4hep/Factories.h
-- |++        exclude: /build/muz/h/w/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/dd4hep-v01-05/DDCore/include/DD4hep/Plugins.h
-- |++        exclude: /build/muz/h/w/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/dd4hep-v01-05/DDCore/include/DD4hep/SurfaceInstaller.h
-- |++        exclude: /build/muz/h/w/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/dd4hep-v01-05/DDCore/include/DD4hep/detail/BasicGrammar_inl.h
-- |++        exclude: /build/muz/h/w/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/dd4hep-v01-05/DDCore/include/XML/UnicodeValues.h
-- |++        exclude: /build/muz/h/w/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/dd4hep-v01-05/DDCore/include/XML/tinyxml.h
-- |++> Dictionary[DDCore] -> G__DD4hepGeo Building dictionary ...
-- |++> Dictionary[DDCore] -> G__DD4hepGeo Uses  DEFAULTS
-- |++> Dictionary[DDCore] -> G__DD4hepProperties Building dictionary ...
-- |++> Dictionary[DDCore] -> G__DD4hepProperties Uses  DEFAULTS
-- |++> Dictionary[DDCore] -> G__DD4hepSegmentations Building dictionary ...
-- |++> Dictionary[DDCore] -> G__DD4hepSegmentations Uses  DEFAULTS
-- |    Package library[DDCore] -> DDCore  ...optional: ADD sources src/JSON/*.cpp [dependent on BOOST]
-- |++> Package library[DDCore] -> DDCore Uses: BOOST
-- |++> Plugin[DDCore] -> DDCorePlugins Uses  DEFAULTS
-- +------------------------------------------- <<<< PACKAGE DDSurfaces >>>> Version: ( 1.2.0 )
-- |++> Package[DDSurfaces] Uses  DEFAULTS
-- Boost version: 1.63.0
-- +------------------------------------------- <<<< PACKAGE DDRec >>>> Version: ( 1.2.0 )
-- |++> Package[DDRec] Uses: DDCoreDDSurfacesboostROOT
-- |    Package library[DDRec] -> DDRec  ...optional: Skip sources src/gear/DDGear.cpp [requires GEAR]
-- |    Package library[DDRec] -> DDRec  ...optional: Skip optional sources src/gear/DDGear.cpp [GEAR Not defined]
-- |++> Package library[DDRec] -> DDRec Uses  DEFAULTS
-- |    Plugin[DDRec] -> DDRecPlugins  ...optional: Skip sources src/gear/createGearForILD.cppsrc/gear/createGearForCLIC.cpp [requires GEAR]
-- |    Plugin[DDRec] -> DDRecPlugins  ...optional: Skip optional sources src/gear/createGearForILD.cppsrc/gear/createGearForCLIC.cpp [GEAR Not defined]
-- |++> Plugin[DDRec] -> DDRecPlugins Uses  DEFAULTS
-- |    Executable[DDRec] -> convertToGear  ...optional: Skip sources src/convertToGear.cc [requires GEAR]
-- |    Executable[DDRec] -> convertToGear  ...optional: Skip optional sources src/convertToGear.cc [GEAR Not defined]
-- |++> Executable[DDRec] -> convertToGear Uses  DEFAULTS
-- |++> Executable[DDRec] -> convertToGear SKIPPED. No sources to build [Use constraint]
-- +------------------------------------------- <<<< PACKAGE DDDetectors >>>> Version: ( 1.2.0 )
-- |++> Package[DDDetectors] Uses: DDRec
-- |++> Plugin[DDDetectors] -> DDDetectors Uses  DEFAULTS
-- +-------------------------------------------------------------------------
-- SKIPPED !!!!!!!!!!!!!!  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- SKIPPED !!!!!!!!!!!!!!  PACKAGE DDG4 / DDG4 SKIPPED! Missing dependency: GEANT4
-- SKIPPED !!!!!!!!!!!!!!  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- SKIPPED !!!!!!!!!!!!!!  Package library[DDG4] -> DDG4 DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Plugin[DDG4] -> DDG4Legacy DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Dictionary[DDG4] -> G__DDG4 DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Plugin[DDG4] -> DDG4Plugins DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Dictionary[DDG4] -> G__DDG4Python DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Dictionary[DDG4] -> G__DDPython DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Package library[DDG4] -> DDPython DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Plugin[DDG4] -> DDG4Python DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Plugin[DDG4] -> DDG4LCIO DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Executable[DDG4] -> g4gdmlDisplay DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Executable[DDG4] -> g4FromXML DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Executable[DDG4] -> dd_sim DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Executable[DDG4] -> pyddg4 DISBALED -- package is not built!
-- +------------------------------------------- <<<< PACKAGE DDCond >>>> Version: ( 1.2.0 )
-- |++> Package[DDCond] Uses: BOOSTDDCore
-- |++> Dictionary[DDCond] -> G__DDCond Building dictionary ...
-- |++> Dictionary[DDCond] -> G__DDCond Uses  DEFAULTS
-- |++> Package library[DDCond] -> DDCond Uses  DEFAULTS
-- |++> Plugin[DDCond] -> DDCondPlugins Uses  DEFAULTS
-- +------------------------------------------- <<<< PACKAGE DDAlign >>>> Version: ( 1.2.0 )
-- |++> Package[DDAlign] Uses: DDCore
-- |++> Package library[DDAlign] -> DDAlign Uses  DEFAULTS
-- |++> Plugin[DDAlign] -> DDAlignPlugins Uses  DEFAULTS
-- +------------------------------------------- <<<< PACKAGE DDEve >>>> Version: ( 1.2.0 )
-- |++> Package[DDEve] Uses: DDCoreROOT
-- |++> Dictionary[DDEve] -> G__DDEve Building dictionary ...
-- |++> Dictionary[DDEve] -> G__DDEve Uses  DEFAULTS
-- |    Plugin[DDEve] -> DDEve  ...optional: Skip sources lcio/LCIOEventHandler.cpp [requires LCIO]
-- |    Plugin[DDEve] -> DDEve  ...optional: Skip optional sources lcio/LCIOEventHandler.cpp [LCIO Not defined]
-- |++> Plugin[DDEve] -> DDEve Uses  DEFAULTS
-- +------------------------------------------- <<<< PACKAGE DDCMS >>>> Version: ( 1.2.0 )
-- |++> Package[DDCMS] Uses: DDCoreCLHEP
-- |++> Plugin[DDCMS] -> DDCMS Uses: DDCoreDDAlignDDCond
-- +------------------------------------------- <<<< PACKAGE DDDB >>>> Version: ( 1.2.0 )
-- |++> Package[DDDB] Uses: DDCoreDDAlignDDCond
-- |++> Plugin[DDDB] -> DDDB Uses: DDCoreDDAlignDDCond
-- |++> Enable CTest environment....BUILD:ON DIRS: DDTest
-- +------------------------------------------- <<<< PACKAGE DDTest >>>> Version: ( 1.2.0 )
-- |    Package[DDTest]  ...optional: Skip optional DDG4 [DDG4 Not defined]
-- |++> Package[DDTest] Uses: DDCoreDDRec
-- |++> Executable[DDTest] -> test_example Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_units Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_surface Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_bitfield64 Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_DetType Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_PolarGridRPhi2 Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_cellDimensions Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_cellDimensionsRPhi2 Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_segmentationHandles Uses  DEFAULTS
-- +------------------------------------------- <<<< PACKAGE UtilityApps >>>> Version: ( 1.2.0 )
-- |++> Package[UtilityApps] Uses: DDCoreROOT
-- |++> Executable[UtilityApps] -> geoDisplay Uses  DEFAULTS
-- |++> Executable[UtilityApps] -> geoConverter Uses  DEFAULTS
-- |++> Executable[UtilityApps] -> geoPluginRun Uses  DEFAULTS
-- |++> Executable[UtilityApps] -> dumpBfield Uses  DEFAULTS
-- |++> Executable[UtilityApps] -> print_materials Uses: DDRec
-- |++> Executable[UtilityApps] -> materialScan Uses: DDRec
-- |++> Executable[UtilityApps] -> graphicalMaterialScan Uses: DDRecROOT
-- |    Executable[UtilityApps] -> dumpdetector  ...optional: Skip sources src/dumpdetector.cpp [requires GEANT4]
-- |    Executable[UtilityApps] -> dumpdetector  ...optional: Skip optional sources src/dumpdetector.cpp [GEANT4 Not defined]
-- |++> Executable[UtilityApps] -> dumpdetector Uses: DDRec
-- |++> Executable[UtilityApps] -> dumpdetector SKIPPED. No sources to build [Use constraint]
-- |    Executable[UtilityApps] -> test_surfaces  ...optional: Skip sources src/test_surfaces.cpp [requires LCIO]
-- |    Executable[UtilityApps] -> test_surfaces  ...optional: Skip optional sources src/test_surfaces.cpp [LCIO Not defined]
-- |++> Executable[UtilityApps] -> test_surfaces Uses: DDRecDDTest
-- |++> Executable[UtilityApps] -> test_surfaces SKIPPED. No sources to build [Use constraint]
-- |    Executable[UtilityApps] -> test_cellid_position_converter  ...optional: Skip sources src/test_cellid_position_converter.cpp [requires LCIO]
-- |    Executable[UtilityApps] -> test_cellid_position_converter  ...optional: Skip optional sources src/test_cellid_position_converter.cpp [LCIO Not defined]
-- |++> Executable[UtilityApps] -> test_cellid_position_converter Uses: DDRecDDTest
-- |++> Executable[UtilityApps] -> test_cellid_position_converter SKIPPED. No sources to build [Use constraint]
-- |++> Dictionary[UtilityApps] -> G__eve Building dictionary ...
-- |++> Dictionary[UtilityApps] -> G__eve Uses  DEFAULTS
-- |++> Executable[UtilityApps] -> teveDisplay Uses: ROOTDDRec
-- 
-- -------------------------------------------------------------------------------
-- Change values with: cmake -D<Variable>=<Value>
-- CMAKE_INSTALL_PREFIX = /build/muz/h/w/tmp/BUILDROOT/6339c14dbc7e702609ccb7aebd305d11/opt/cmssw/slc6_amd64_gcc630/external/dd4hep/v01-05-cms
-- CMAKE_BUILD_TYPE = Release
-- BUILD_TESTING = ON
-- INSTALL_DOC = OFF
-- CMAKE_PREFIX_PATH =
--    /build/muz/h/w/slc6_amd64_gcc630/external/clhep/2.4.0.0;
-- CMAKE_MODULE_PATH =
--    /build/muz/h/w/BUILD/slc6_amd64_gcc630/external/dd4hep/v01-05-cms/dd4hep-v01-05/cmake;
-- -------------------------------------------------------------------------------
-- 
-- Configuring done
-- Generating done
```

**Comment by smuzaffar** [comment]
master also failed with same error. Note that we are using gcc version 6.3.0. I noticed that for compilation it uses  `-std=c++14` while for rootcling it passes ` -std=c++11 `
is this the reason behind this message
```
In file included from /build/muz/h/w/slc6_amd64_gcc630/external/gcc/6.3.0-cms/bin/../lib/gcc/x86_64-unknown-linux-gnu/6.3.0/../../../../include/c++/6.3.0/experimental/string_view:39:
/build/muz/h/w/slc6_amd64_gcc630/external/gcc/6.3.0-cms/bin/../lib/gcc/x86_64-unknown-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/c++14_warning.h:32:2: error: This file requires compiler and library support for the forthcoming ISO C++ 2014 standard. This support is currently experimental, and must be enabled with the -std=c++1y or -std=gnu++1y compiler options.
#error This file requires compiler and library support for the forthcoming \

```

**Comment by andresailer** [comment]
Try adding `-DCMAKE_CXX_STANDARD=14` to the cmake call
Only works for dd4hep master

**Comment by smuzaffar** [comment]
thanks it worked with `-DCMAKE_CXX_STANDARD=14`
Do you know if dd4hep works with root 6.10?

**Comment by petricm** [comment]
Yes, we were running the CI some time ago with 6.10, but there are a few new developments in master that require 6.12, but master should also compile with 6.10.

**Comment by smuzaffar** [comment]
With root 6.10, I get this error (full build log is available here https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3690/25798/external/dd4hep/v01-05x/log )
```
-- |++> Plugin[DDCore] -> DDCorePlugins Uses  DEFAULTS
CMake Error at /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc6_amd64_gcc630/lcg/root/6.10.09-jpkldn/cmake/ROOTConfig.cmake:137 (message):
  ROOT component Gdml not found
```

**Comment by petricm** [comment]
Thank you for pointing this out, there is a missing IF if the CMake, if you remove this

https://github.com/AIDASoft/DD4hep/blob/ea370e961431697d6cc08d6b1cd8ec75cf3a4b1b/DDCore/CMakeLists.txt#L71-L75

it should work.

**Comment by smuzaffar** [comment]
thanks, removing DDGDMLPlugins worked.

**Comment by MarkusFrankATcernch** [comment]
I remember there was once an issue with ROOT and the std compliance. I don't know if this is already resolved or not but dd4hep should not be built with a std=c++XX version higher than the ROOT version.
Otherwise cling/clang may not work properly with dd4hep. This for sure is true with earlier releases of ROOT.
