### PR TITLE
Remove unused template function calling non existing function.

### PR DESCRIPTION
**Pull request by ahennequ**
Remove unused template function calling non existing function.

This function is causing a build error when trying to compile with nvcc < 13.2. It works fine with other compilers (eg. gcc, clang) because the template function is never instantiated, so the compiler should be ignoring it. This is a bug in nvcc which doesn't ignore it and throws a compilation error. This issue is fixed in nvcc 13.2 but is present in all prior versions.

As part of the Gaudi-Allen convergence work we want to be able to compile, or at least parse DD4HEP headers with nvcc (for the host part).

FYI @sponce 

BEGINRELEASENOTES

* Shapes.h: Remove unused template function calling non existing function. (fix nvcc build)

ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
Dear @ahennequ 

Thank you for your contribution, could you please keep the BEGIN/ENDRELEASENOTES in the PR description?

**Comment by ahennequ** [comment]
> Dear @ahennequ
> 
> Thank you for your contribution, could you please keep the BEGIN/ENDRELEASENOTES in the PR description?

I've added them back

**Comment by MarkusFrankATcernch** [comment]
TwistedTube is a construct from CMS. The fact this constructor is not used in the DD4hep code 
does not mean it is unused. Hence, if we want to remove it for nvcc, we need a proper #if !defined(...)  ... #endif

**Comment by andresailer** [comment]
I think the point is that the make(str, dbl, dbl, dbl) function does not exist, so even cms cannot use this templated function?

**Comment by MarkusFrankATcernch** [comment]
@andresailer I missed this one. Then of course the constructor can be suppressed.
