### ISSUE TITLE
failed to build with gcc73 and root 6.10

### ISSUE THREAD

**Issue by smuzaffar** [AIDASoft/DD4hep#300]
We are trying to include dd4hep in CMS software and now we see the latest dd4hep does not build with
- Root: 6.10
- Gcc: 7.3.1
- dd4hep: https://github.com/AIDASoft/DD4hep/commit/52e6d2fee62af2c264196ca4e4411e1f877efc96

We get this type of build errors ( full cmake/build log is available here https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3702/25819/external/dd4hep/v01-05x/log )

```
../lcg/root/6.10.09-jndmai/include/RStringView.h:67:17: error: expected type-specifier
        operator std::string_view() const { return std::string_view(fData,fLength); }
```

**Comment by andresailer** [comment]
I get `Authorization Failed` when I try to see the build log.
Which c++ standard are you using?

**Comment by smuzaffar** [comment]
here is cmake output [a]. It uses c++1z  standard but on command line [b]  I see that it also adds c++14 `-std=c++1z   -pthread -O3 -DNDEBUG -fPIC   -std=c++14 `
[a]
```
+ cmake -DCMAKE_INSTALL_PREFIX=/opt/cmssw/slc6_amd64_gcc700/external/dd4hep/v01-05x -DBoost_NO_BOOST_CMAKE=ON -DCMAKE_PREFIX_PATH=/opt/cmssw/slc6_amd64_gcc700/external/clhep/2.4.0.0-jndmai -DDD4HEP_USE_XERCESC=ON -DXERCESC_ROOT_DIR=/opt/cmssw/slc6_amd64_gcc700/external/xerces-c/3.1.3-jndmai -DDD4HEP_USE_PYROOT=ON -DCMAKE_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=Release ../dd4hep-v01-05x
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Could NOT find LATEX (missing: LATEX_COMPILER) 
-- No LaTeX found, cannot compile user manual.
-- The CXX compiler identification is GNU 7.3.1
-- Check for working CXX compiler: /opt/cmssw/slc6_amd64_gcc700/external/gcc/7.0.0-jndmai/bin/c++
-- Check for working CXX compiler: /opt/cmssw/slc6_amd64_gcc700/external/gcc/7.0.0-jndmai/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- INCLUDING DD4hepBuild.cmake
-- The C compiler identification is GNU 7.3.1
-- Check for working C compiler: /opt/cmssw/slc6_amd64_gcc700/external/gcc/7.0.0-jndmai/bin/cc
-- Check for working C compiler: /opt/cmssw/slc6_amd64_gcc700/external/gcc/7.0.0-jndmai/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- DD4hep_configure_output: set CMAKE_INSTALL_PREFIX to /opt/cmssw/slc6_amd64_gcc700/external/dd4hep/v01-05x
-- ROOT_VERSION: 6.10.09
-- Boost version: 1.63.0
-- Performing Test CXX_FLAG_WORKS__Wall
-- Performing Test CXX_FLAG_WORKS__Wall - Success
-- Adding -Wall to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS__Wextra
-- Performing Test CXX_FLAG_WORKS__Wextra - Success
-- Adding -Wextra to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS__pedantic
-- Performing Test CXX_FLAG_WORKS__pedantic - Success
-- Adding -pedantic to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS__Wshadow
-- Performing Test CXX_FLAG_WORKS__Wshadow - Success
-- Adding -Wshadow to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS__Wformat_security
-- Performing Test CXX_FLAG_WORKS__Wformat_security - Success
-- Adding -Wformat-security to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS__Wno_long_long
-- Performing Test CXX_FLAG_WORKS__Wno_long_long - Success
-- Adding -Wno-long-long to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS__Wdeprecated
-- Performing Test CXX_FLAG_WORKS__Wdeprecated - Success
-- Adding -Wdeprecated to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS__fdiagnostics_color=auto
-- Performing Test CXX_FLAG_WORKS__fdiagnostics_color=auto - Success
-- Adding -fdiagnostics-color=auto to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS_FTLS_global_dynamic
-- Performing Test CXX_FLAG_WORKS_FTLS_global_dynamic - Success
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found XercesC: /opt/cmssw/slc6_amd64_gcc700/external/xerces-c/3.1.3-jndmai/lib/libxerces-c.so  
-- +------------------------------------------- <<<< PACKAGE DDParsers >>>> Version: ( 1.5.0 )
-- |++> Package[DDParsers] Uses: ROOT
-- Boost version: 1.63.0
-- |    Package library[DDParsers] -> DDParsers  ...optional: ADD sources src/parsers/*.cpp [dependent on BOOST]
-- |++> Package library[DDParsers] -> DDParsers Uses: BOOST
-- +------------------------------------------- <<<< PACKAGE DDCore >>>> Version: ( 1.5.0 )
-- |++> Package[DDCore] Uses: ROOTDDParsersXERCESC
-- |++> Dictionary[DDCore] -> G__DD4hep Building dictionary ...
-- |++> Dictionary[DDCore] -> G__DD4hep Uses  DEFAULTS
-- |++        exclude: /opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/DDCore/include/DD4hep/DetFactoryHelper.h
-- |++        exclude: /opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/DDCore/include/DD4hep/Factories.h
-- |++        exclude: /opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/DDCore/include/DD4hep/Plugins.h
-- |++        exclude: /opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/DDCore/include/DD4hep/SurfaceInstaller.h
-- |++        exclude: /opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/DDCore/include/DD4hep/detail/BasicGrammar_inl.h
-- |++        exclude: /opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/DDCore/include/XML/UnicodeValues.h
-- |++        exclude: /opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/DDCore/include/XML/tinyxml.h
-- |++> Dictionary[DDCore] -> G__DD4hepGeo Building dictionary ...
-- |++> Dictionary[DDCore] -> G__DD4hepGeo Uses  DEFAULTS
-- |++> Dictionary[DDCore] -> G__DD4hepProperties Building dictionary ...
-- |++> Dictionary[DDCore] -> G__DD4hepProperties Uses  DEFAULTS
-- |++> Dictionary[DDCore] -> G__DD4hepSegmentations Building dictionary ...
-- |++> Dictionary[DDCore] -> G__DD4hepSegmentations Uses  DEFAULTS
-- |    Package library[DDCore] -> DDCore  ...optional: ADD sources src/JSON/*.cpp [dependent on BOOST]
-- |++> Package library[DDCore] -> DDCore Uses: BOOST
-- |++> Plugin[DDCore] -> DDCorePlugins Uses  DEFAULTS
-- +------------------------------------------- <<<< PACKAGE DDSurfaces >>>> Version: ( 1.5.0 )
-- |++> Package[DDSurfaces] Uses  DEFAULTS
-- Boost version: 1.63.0
-- +------------------------------------------- <<<< PACKAGE DDRec >>>> Version: ( 1.5.0 )
-- |++> Package[DDRec] Uses: DDCoreDDSurfacesboostROOT
-- |    Package library[DDRec] -> DDRec  ...optional: Skip sources src/gear/DDGear.cpp [requires GEAR]
-- |    Package library[DDRec] -> DDRec  ...optional: Skip optional sources src/gear/DDGear.cpp [GEAR Not defined]
-- |++> Package library[DDRec] -> DDRec Uses  DEFAULTS
-- |    Plugin[DDRec] -> DDRecPlugins  ...optional: Skip sources src/gear/createGearForILD.cppsrc/gear/createGearForCLIC.cppsrc/gear/createGearForSiD.cpp [requires GEAR]
-- |    Plugin[DDRec] -> DDRecPlugins  ...optional: Skip optional sources src/gear/createGearForILD.cppsrc/gear/createGearForCLIC.cppsrc/gear/createGearForSiD.cpp [GEAR Not defined]
-- |++> Plugin[DDRec] -> DDRecPlugins Uses  DEFAULTS
-- |    Executable[DDRec] -> convertToGear  ...optional: Skip sources src/convertToGear.cc [requires GEAR]
-- |    Executable[DDRec] -> convertToGear  ...optional: Skip optional sources src/convertToGear.cc [GEAR Not defined]
-- |++> Executable[DDRec] -> convertToGear Uses  DEFAULTS
-- |++> Executable[DDRec] -> convertToGear SKIPPED. No sources to build [Use constraint]
-- +------------------------------------------- <<<< PACKAGE DDDetectors >>>> Version: ( 1.5.0 )
-- |++> Package[DDDetectors] Uses: DDRec
-- |++> Plugin[DDDetectors] -> DDDetectors Uses  DEFAULTS
-- +-------------------------------------------------------------------------
-- SKIPPED !!!!!!!!!!!!!!  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- SKIPPED !!!!!!!!!!!!!!  PACKAGE DDG4 / DDG4 SKIPPED! Missing dependency: GEANT4
-- SKIPPED !!!!!!!!!!!!!!  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- CLHEP_LIBRARIES  
-- SKIPPED !!!!!!!!!!!!!!  Package library[DDG4] -> DDG4 DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Plugin[DDG4] -> DDG4Legacy DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Dictionary[DDG4] -> G__DDG4 DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Plugin[DDG4] -> DDG4Plugins DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Dictionary[DDG4] -> G__DDG4Python DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Dictionary[DDG4] -> G__DDPython DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Package library[DDG4] -> DDPython DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Plugin[DDG4] -> DDG4Python DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Plugin[DDG4] -> DDG4LCIO DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Executable[DDG4] -> g4gdmlDisplay DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Executable[DDG4] -> g4FromXML DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Executable[DDG4] -> dd_sim DISBALED -- package is not built!
-- SKIPPED !!!!!!!!!!!!!!  Executable[DDG4] -> pyddg4 DISBALED -- package is not built!
-- +------------------------------------------- <<<< PACKAGE DDCond >>>> Version: ( 1.5.0 )
-- |++> Package[DDCond] Uses: BOOSTDDCore
-- |++> Dictionary[DDCond] -> G__DDCond Building dictionary ...
-- |++> Dictionary[DDCond] -> G__DDCond Uses  DEFAULTS
-- |++> Package library[DDCond] -> DDCond Uses  DEFAULTS
-- |++> Plugin[DDCond] -> DDCondPlugins Uses  DEFAULTS
-- +------------------------------------------- <<<< PACKAGE DDAlign >>>> Version: ( 1.5.0 )
-- |++> Package[DDAlign] Uses: DDCore
-- |++> Package library[DDAlign] -> DDAlign Uses  DEFAULTS
-- |++> Plugin[DDAlign] -> DDAlignPlugins Uses  DEFAULTS
-- +------------------------------------------- <<<< PACKAGE DDEve >>>> Version: ( 1.5.0 )
-- |++> Package[DDEve] Uses: DDCoreROOT
-- |++> Dictionary[DDEve] -> G__DDEve Building dictionary ...
-- |++> Dictionary[DDEve] -> G__DDEve Uses  DEFAULTS
-- |++        exclude: /opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/DDEve/include/DDEve/Utilities.h
-- |++        exclude: /opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/DDEve/include/DDEve/ParticleActors.h
-- |++        exclude: /opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/DDEve/include/DDEve/HitActors.h
-- |++        exclude: /opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/DDEve/include/DDEve/Factories.h
-- |    Plugin[DDEve] -> DDEve  ...optional: Skip sources lcio/LCIOEventHandler.cpp [requires LCIO]
-- |    Plugin[DDEve] -> DDEve  ...optional: Skip optional sources lcio/LCIOEventHandler.cpp [LCIO Not defined]
-- |++> Plugin[DDEve] -> DDEve Uses  DEFAULTS
-- +------------------------------------------- <<<< PACKAGE DDCMS >>>> Version: ( 1.5.0 )
-- |++> Package[DDCMS] Uses: DDCoreCLHEP
-- |++> Plugin[DDCMS] -> DDCMS Uses: DDCoreDDAlignDDCond
-- +------------------------------------------- <<<< PACKAGE DDDB >>>> Version: ( 1.5.0 )
-- |++> Package[DDDB] Uses: DDCoreDDAlignDDCond
-- |++> Plugin[DDDB] -> DDDB Uses: DDCoreDDAlignDDCond
-- |++> Enable CTest environment....BUILD:ON DIRS: DDTest
-- +------------------------------------------- <<<< PACKAGE DDTest >>>> Version: ( 1.5.0 )
-- |    Package[DDTest]  ...optional: Skip optional DDG4 [DDG4 Not defined]
-- |++> Package[DDTest] Uses: DDCoreDDRec
-- |++> Executable[DDTest] -> test_example Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_units Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_surface Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_bitfield64 Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_bitfieldcoder Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_DetType Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_PolarGridRPhi2 Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_cellDimensions Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_cellDimensionsRPhi2 Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_segmentationHandles Uses  DEFAULTS
-- +------------------------------------------- <<<< PACKAGE UtilityApps >>>> Version: ( 1.5.0 )
-- |++> Package[UtilityApps] Uses: DDCoreROOT
-- |++> Executable[UtilityApps] -> geoDisplay Uses  DEFAULTS
-- |++> Executable[UtilityApps] -> geoConverter Uses  DEFAULTS
-- |++> Executable[UtilityApps] -> geoPluginRun Uses  DEFAULTS
-- |++> Executable[UtilityApps] -> dumpBfield Uses  DEFAULTS
-- |++> Executable[UtilityApps] -> print_materials Uses: DDRec
-- |++> Executable[UtilityApps] -> materialScan Uses: DDRec
-- |++> Executable[UtilityApps] -> graphicalMaterialScan Uses: DDRecROOT
-- |    Executable[UtilityApps] -> dumpdetector  ...optional: Skip sources src/dumpdetector.cpp [requires GEANT4]
-- |    Executable[UtilityApps] -> dumpdetector  ...optional: Skip optional sources src/dumpdetector.cpp [GEANT4 Not defined]
-- |++> Executable[UtilityApps] -> dumpdetector Uses: DDRec
-- |++> Executable[UtilityApps] -> dumpdetector SKIPPED. No sources to build [Use constraint]
-- |    Executable[UtilityApps] -> test_surfaces  ...optional: Skip sources src/test_surfaces.cpp [requires LCIO]
-- |    Executable[UtilityApps] -> test_surfaces  ...optional: Skip optional sources src/test_surfaces.cpp [LCIO Not defined]
-- |++> Executable[UtilityApps] -> test_surfaces Uses: DDRecDDTest
-- |++> Executable[UtilityApps] -> test_surfaces SKIPPED. No sources to build [Use constraint]
-- |    Executable[UtilityApps] -> test_cellid_position_converter  ...optional: Skip sources src/test_cellid_position_converter.cpp [requires LCIO]
-- |    Executable[UtilityApps] -> test_cellid_position_converter  ...optional: Skip optional sources src/test_cellid_position_converter.cpp [LCIO Not defined]
-- |++> Executable[UtilityApps] -> test_cellid_position_converter Uses: DDRecDDTest
-- |++> Executable[UtilityApps] -> test_cellid_position_converter SKIPPED. No sources to build [Use constraint]
-- |++> Dictionary[UtilityApps] -> G__eve Building dictionary ...
-- |++> Dictionary[UtilityApps] -> G__eve Uses  DEFAULTS
-- |++> Executable[UtilityApps] -> teveDisplay Uses: ROOTDDRec
-- 
-- -------------------------------------------------------------------------------
-- Change values with: cmake -D<Variable>=<Value>
-- CMAKE_INSTALL_PREFIX = /opt/cmssw/slc6_amd64_gcc700/external/dd4hep/v01-05x
-- CMAKE_BUILD_TYPE = Release
-- CMAKE_CXX_FLAGS = -ftls-model=global-dynamic -fdiagnostics-color=auto -Wdeprecated -Wno-long-long -Wformat-security -Wshadow -pedantic -Wextra -Wall  -D__ROOFIT_NOBANNER -pipe -m64 -fsigned-char -fPIC -pthread -std=c++1z          -pthread
-- CMAKE_CXX_STANDARD = 14
-- CMAKE_SHARED_LINKER_FLAGS =  -pthread -Wl,--no-undefined
-- BUILD_TESTING = ON
-- CMAKE_PREFIX_PATH =
--    /opt/cmssw/slc6_amd64_gcc700/external/clhep/2.4.0.0-jndmai;
-- CMAKE_MODULE_PATH =
--    /opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/cmake;
-- -------------------------------------------------------------------------------
-- 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    DD4HEP_USE_PYROOT
```

[b] 
```
cd /opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/build/DDCore && /opt/cmssw/slc6_amd64_gcc700/external/gcc/7.0.0-jndmai/bin/c++  -DBOOST_SPIRIT_USE_PHOENIX_V3 -DDD4HEP_USE_XERCESC -DDDCore_EXPORTS -D__ROOFIT_NOBANNER -isystem /opt/cmssw/slc6_amd64_gcc700/lcg/root/6.10.09-jndmai/include -isystem /opt/cmssw/slc6_amd64_gcc700/external/xerces-c/3.1.3-jndmai/include -I/opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/DDParsers/include -I/opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/DDCore/include -isystem /opt/cmssw/slc6_amd64_gcc700/external/boost/1.63.0-jndmai/include -I/opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/GaudiPluginService  -ftls-model=global-dynamic -fdiagnostics-color=auto -Wdeprecated -Wno-long-long -Wformat-security -Wshadow -pedantic -Wextra -Wall  -D__ROOFIT_NOBANNER -pipe -m64 -fsigned-char -fPIC -pthread -std=c++1z          -pthread -O3 -DNDEBUG -fPIC   -std=c++14 -o CMakeFiles/DDCore.dir/src/AlignmentData.cpp.o -c /opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/DDCore/src/AlignmentData.cpp
In file included from /opt/cmssw/slc6_amd64_gcc700/lcg/root/6.10.09-jndmai/include/TString.h:28:0,
                 from /opt/cmssw/slc6_amd64_gcc700/lcg/root/6.10.09-jndmai/include/TNamed.h:26,
                 from /opt/cmssw/slc6_amd64_gcc700/lcg/root/6.10.09-jndmai/include/TGeoPhysicalNode.h:15,
                 from /opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/DDCore/include/DD4hep/Objects.h:36,
                 from /opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/DDCore/include/DD4hep/DetElement.h:19,
                 from /opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/DDCore/include/DD4hep/AlignmentData.h:18,
                 from /opt/cmssw/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-05x/dd4hep-v01-05x/DDCore/src/AlignmentData.cpp:15:
/opt/cmssw/slc6_amd64_gcc700/lcg/root/6.10.09-jndmai/include/RStringView.h:67:17: error: expected type-specifier
        operator std::string_view() const { return std::string_view(fData,fLength); }
```

**Comment by petricm** [comment]
As far as I see you build ROOT 6.10 with `c++1z` and then try to build DD4hep against this using `c++14`. The standards have to be aligned.

**Comment by smuzaffar** [comment]
ok thanks, I am now building dd4hep with c++1z (using `-DCMAKE_CXX_STANDARD=17` ) and it did build successfully. I still see `-sdt=` option being added multiple times (2 to 3 times), is this on purpose or bug.
```
-std=c++1z  -pthread -std=c++11 -O3 -DNDEBUG -fPIC   -Wno-unused-function -Wno-deprecated -Wno-shadow -std=c++1z -o CMakeFiles/DD4hepGaudiPluginMgr.dir/interface/DD4hep.cpp.o
```
```
-std=c++1z -pthread -O3 -DNDEBUG -fPIC   -std=c++1z -o CMakeFiles/DDSegmentation.dir/src/bla.cpp.o
```
```
-std=c++1z -pthread -std=c++11 -O3 -DNDEBUG   -Wno-deprecated -std=c++1z -o CMakeFiles/listcomponents.dir/src/listcomponents.cpp.
```
```
-std=c++1z -pthread -O3 -DNDEBUG -fPIC   -std=c++1z -o CMakeFiles/DDParsers.dir/src/ToStream.cpp.o
```

**Comment by petricm** [comment]
The `c++11` flags come from Geant4 probably, from the line `include( ${Geant4_USE_FILE} )` but this is then overwritten in all targets by `-DCMAKE_CXX_STANDARD=`

**Comment by petricm** [comment]
Sorry, no it's actually coming form the Gaudi plugin manager, we have to tidy this up a bit.

**Comment by MarkusFrankATcernch** [comment]
cross post issue https://github.com/AIDASoft/DD4hep/issues/298

I remember there was once an issue with ROOT and the std compliance. I don't know if this is already resolved or not but dd4hep should not be built with a std=c++XX version higher than the ROOT version.
Otherwise cling/clang may not work properly with dd4hep. This for sure is true with earlier releases of ROOT.
