### ISSUE TITLE
ROOT TGeoMatrix interface change

### ISSUE THREAD

**Issue by iarspider** [AIDASoft/DD4hep#426]
Dear DD4Hep developers,

dd4hep version 01-05 (and, I think, master as well, since the code in question is unchanged) fails to build with gcc 6.2 (or newer) and HEAD version of ROOT. The error message is "invalid initialization of non-const reference of type ‘TGeoMatrix&’ from an rvalue of type ‘TGeoMatrix’". 

Thanks,
Ivan for the GENSER team

 - OS version: SLC6 (not tested, but will likely fail with Centos 7)
 - Compiler version: GCC 6.2, 7.3.0, 8.1.0
 - DD4hep version: tag v01-05
 - Reproduced by: building against ROOT-head.
 - Build log: https://cernbox.cern.ch/index.php/s/TxSdekx7XSLl9bA
Important part:
```
[ 44%] Building CXX object UtilityApps/CMakeFiles/geoConverter.dir/src/converter.cpp.o
/mnt/build/jenkins/workspace/lcg_personal_experimental/BUILDTYPE/Release/COMPILER/gcc62binutils/LABEL/slc6/build/projects/DD4hep-01-05/src/DD4hep/01-05/DDCore/src/plugins/LCDDConverter.cpp: In member function ‘virtual xml_h dd4hep::detail::LCDDConverter::handleSolid(const string&, const TGeoShape*) const’:
/mnt/build/jenkins/workspace/lcg_personal_experimental/BUILDTYPE/Release/COMPILER/gcc62binutils/LABEL/slc6/build/projects/DD4hep-01-05/src/DD4hep/01-05/DDCore/src/plugins/LCDDConverter.cpp:552:39: error: invalid initialization of non-const reference of type ‘TGeoMatrix&’ from an rvalue of type ‘TGeoMatrix’
         TGeoMatrix& linv = lm->Inverse()
                            ~~~~~~~~~~~^~
/mnt/build/jenkins/workspace/lcg_personal_experimental/BUILDTYPE/Release/COMPILER/gcc62binutils/LABEL/slc6/build/projects/DD4hep-01-05/src/DD4hep/01-05/DDCore/src/plugins/LCDDConverter.cpp:571:39: error: invalid initialization of non-const reference of type ‘TGeoMatrix&’ from an rvalue of type ‘TGeoMatrix’
         TGeoMatrix& rinv = rm->Inverse()
                            ~~~~~~~~~~~^~
[ 44%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/Geant4Exec.cpp.o
[ 44%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/Geant4Field.cpp.o
[ 44%] Building CXX object DDCond/CMakeFiles/DDCond.dir/src/ConditionsOperators.cpp.o
[ 44%] Building CXX object DDEve/CMakeFiles/DDEve.dir/src/DDEvePlugins.cpp.o
make[6]: *** [DDCore/CMakeFiles/DDCorePlugins.dir/src/plugins/LCDDConverter.cpp.o] Error 1
```

**Comment by mrodozov** [comment]
When I build with gcc7 still has this 
```
/build/mrodozov/builds/build/update_root/build_dd4hep_with_latest_root614/BUILD/slc6_amd64_gcc700/external/dd4hep/v01-08x-cms/dd4hep-v01-08x/DDCore/src/plugins/Compact2Objects.cpp:1118:101: error: taking ad\
dress of temporary [-fpermissive]
   Transform3D  tr_volume(detail::matrix::_transform(&anchor.nominal().worldTransformation().Inverse()));
```

**Comment by andresailer** [comment]
So we have to add an implementation of `_transform` that takes a `TGeoMatrix const&`
https://github.com/AIDASoft/DD4hep/blob/dff301818cfa026b953917bccf4d91361bd8a1e3/DDCore/src/MatrixHelpers.cpp#L103-L114

and drop the `&` from the problematic line?

**Comment by mrodozov** [comment]
I confirm with gcc7 builds with this changes:
https://github.com/AIDASoft/DD4hep/compare/master...cms-externals:cms/master/dfd9760-with-fix
(the changes on DDCore/CMakeLists.txt are not related to this)
Cheers,
M.
