### ISSUE TITLE
GCC 4.9 compilation error in Geant4InputHandling.cpp

### ISSUE THREAD

**Issue by shaojunlu** [AIDASoft/DD4hep#320]
- OS version: SLC6
 - Compiler version: GCC 4.9.3 (CERN AFS)
    - source /afs/cern.ch/sw/lcg/contrib/gcc/4.9.3/x86_64-slc6/setup.sh
    - export PATH=/afs/cern.ch/sw/lcg/releases/LCG_87/Python/2.7.10/x86_64-slc6-gcc49-opt/bin:$PATH
    - export LD_LIBRARY_PATH=/afs/cern.ch/sw/lcg/releases/LCG_87/Python/2.7.10/x86_64-slc6-gcc49-opt/lib:$LD_LIBRARY_PATH
    - export CC=gcc
    - export CXX=g++

 - DD4hep version: https://github.com/AIDASoft/DD4hep/blob/master/DDG4/src/Geant4InputHandling.cpp#L434
 - Reproduced by: ILCSoft nightly build with gcc4.9.3
 - Error: 
      - /scratch/nbuilds/gcc49/2018-02-27/DD4hep/HEAD/DDG4/src/Geant4InputHandling.cpp: In lambda function:
      - /scratch/nbuilds/gcc49/2018-02-27/DD4hep/HEAD/DDG4/src/Geant4InputHandling.cpp:434:133: error: use of deleted function 'std::basic_stringstream<char>::basic_stringstream(const std::basic_stringstream<char>&)'
      - caller->debug("Rejecting PDGs: %s", [&rejectPDGs](){ std::stringstream str; for (int i: rejectPDGs) { str  << i << ", "; } return str;}().str().c_str());

 - Last update: https://github.com/AIDASoft/DD4hep/commit/0d8ae7116527b336222550031de05634a4982d3b#diff-9c36d2d64a01930018f1519715a3b4f9R434

**Comment by petricm** [comment]
I think this is a bug of the compiler. Given that LCG release 89 which was released in July last year also dropped GCC 4.9 would it be possible that you consider going to at least GCC 5.4. To my knowledge no experiment is anymore using 4.9 in fact the last LCG(93) release has only GCC 6 and 7.

**Comment by shaojunlu** [comment]
@petricm Hi, Marko, thank you very much! ILC/ILD may consider to use another GCC version.

**Comment by gaede** [comment]
Can we please simply change this debug statement such that it compiles w/ gcc4.9. Moving to a new compiler is much more involved...

**Comment by andresailer** [comment]
Change to this:
```
caller->debug("Rejecting PDGs: %s", &rejectPDGs{ std::stringstream str; for (int i: rejectPDGs) { str << i << ", "; } return str.str();}().c_str());
```
gcc 4.9 does not implement the needed move operation. stringstreams cannot be copied. But if we return a string it works. (We cannot return a c_str aka char* because it points to a local in the function and.)
